spring.data.mongodb.uri=mongodb+srv://codefreak97_db_user:ustFGjnUpzC6BBfv@cluster0.5w19svg.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true